[versions]
# Runtime
awsSdk = "1.1.1" # Note: Kotlin SDK, not Java SDK
lambdaJavaCore = "1.2.3"
lambdaJavaEvents = "3.11.4"

# Build
kotlin = "1.9.23"
shadow = "8.1.1"

# Test
junit5 = "5.10.2"

[libraries]
# Runtime
awssdk-bom = { group = "aws.sdk.kotlin", name = "bom", version.ref = "awsSdk" } # Bill-of-Materials
awssdk-s3 = { group = "aws.sdk.kotlin", name = "s3" }
lambda-core = {group = "com.amazonaws", name = "aws-lambda-java-core", version.ref="lambdaJavaCore"}
lambda-events = {group = "com.amazonaws", name = "aws-lambda-java-events", version.ref="lambdaJavaEvents"}

# Test
junit-5-api = {module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5"}
junit-5 = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

# Infrastructure
cdk = { module = "software.amazon.awscdk:aws-cdk-lib", version = { strictly = "2.133.0" } }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
